### ISSUE TITLE
You can click on a picked lock

### ISSUE THREAD

**Issue by StastnyJ** [QRGameStudio/game-lock-picker-simulator#1]
After you pick a lock and the game shows the right answer, you can still click (multiple times) on the single one lock in order to get incredibly high score.

**Comment by StastnyJ** [comment]
https://user-images.githubusercontent.com/10522096/109376454-d6f16700-78c4-11eb-8891-4044b8ef702a.mp4

**Comment by esoadamo** [comment]
Thanks, fixed now!
